# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personas
  template:
    metadata:
      labels:
        app: personas
    spec:
      containers:
        - name: app
          image: carboy35/personas:firsttry
          ports:
            - containerPort: 8093
          env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysql:3306/prueba
          imagePullPolicy: Always
