# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: personas
spec:
  selector:
    app: personas
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer