package cl.ionix.entities;
// Generated 21-jul-2020 7:37:34 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmpEmpresas generated by hbm2java
 */
@Entity
@Table(name = "emp_empresas", catalog = "prueba")
public class EmpEmpresas implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set<RlcEmpresasPersonas> rlcEmpresasPersonases = new HashSet<RlcEmpresasPersonas>(0);

	public EmpEmpresas() {
	}

	public EmpEmpresas(String nombre, Set<RlcEmpresasPersonas> rlcEmpresasPersonases) {
		this.nombre = nombre;
		this.rlcEmpresasPersonases = rlcEmpresasPersonases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empEmpresas")
	public Set<RlcEmpresasPersonas> getRlcEmpresasPersonases() {
		return this.rlcEmpresasPersonases;
	}

	public void setRlcEmpresasPersonases(Set<RlcEmpresasPersonas> rlcEmpresasPersonases) {
		this.rlcEmpresasPersonases = rlcEmpresasPersonases;
	}

}
