package cl.ionix.entities;
// Generated 21-jul-2020 7:37:34 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RlcEmpresasPersonas generated by hbm2java
 */
@Entity
@Table(name = "rlc_empresas_personas", catalog = "prueba")
public class RlcEmpresasPersonas implements java.io.Serializable {

	private Integer idEmpPersonas;
	private EmpEmpresas empEmpresas;
	private PerPersonas perPersonas;

	public RlcEmpresasPersonas() {
	}

	public RlcEmpresasPersonas(EmpEmpresas empEmpresas, PerPersonas perPersonas) {
		this.empEmpresas = empEmpresas;
		this.perPersonas = perPersonas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_emp_personas", unique = true, nullable = false)
	public Integer getIdEmpPersonas() {
		return this.idEmpPersonas;
	}

	public void setIdEmpPersonas(Integer idEmpPersonas) {
		this.idEmpPersonas = idEmpPersonas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public EmpEmpresas getEmpEmpresas() {
		return this.empEmpresas;
	}

	public void setEmpEmpresas(EmpEmpresas empEmpresas) {
		this.empEmpresas = empEmpresas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public PerPersonas getPerPersonas() {
		return this.perPersonas;
	}

	public void setPerPersonas(PerPersonas perPersonas) {
		this.perPersonas = perPersonas;
	}

}
